#To run DeckAlchemist in Docker: docker-compose build && docker-compose up
version: '3'

networks:
  mainnetwork:
    driver: bridge
    
services:
  deckalchemist.api:
    image: deckalchemist.api
    build:
      context: ./
      dockerfile: Dockerfile-Api
    ports: 
        - 5000:80
    depends_on:
        - mongodb
    links:
        - mongodb
    networks:
        - mainnetwork
    environment:
        - MONGO_URI=mongodb://mongo
    

  deckalchemist.collector:
    image: deckalchemist.collector
    build:
      context: ./
      dockerfile: Dockerfile-Collector
    ports: 
        - 3865:80
    depends_on:
        - mongodb
    links:
        - mongodb
    networks:
        - mainnetwork
    environment:
        - MONGO_URI=mongodb://mongo

  deckalchemist.webapp:
    image: deckalchemist.webapp
    build:
      context: ./
      dockerfile: Dockerfile-WebApp
    ports: 
        - 80:80
    depends_on:
        - mongodb
    links:
        - mongodb
    networks:
        - mainnetwork
    environment:
        - MONGO_URI=mongodb://mongo

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/data/logs
    volumes:
      - ~/colossus/data/mongo:/data
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/data/logs
    networks:
        mainnetwork:
            aliases:
                - mongo