version: '3'
services:
  api:
    build:  ./DeckAlchemist.WebApp.Api/.
    container_name: "deckalchemist-webapi"
    links:
      - mongodb
    depends_on:
      - mongodb
    ports:
      - 5000:80
      #TODO HTTPS Only
  
  web:
    build: ./DeckAlchemist.WebApp/.
    container_name: "deckalchemist-web"
    links:
      - api
    depends_on:
      - api
    ports:
      - 80:80
      #TODO: HTTPS
  
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_DATA_DIR=/data/db #TODO: Persistant storage
      - MONGO_LOG_DIR=/dev/null
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null
    